### ISSUE TITLE
add license?

### ISSUE THREAD

**Issue by japhir** [Tripati-Lab/BayClump#11]
Hi! Looking at your project again, I was thinking about how I could potentially use the software. But I could not find any license information. Could you add the license of your choice? If you don't know much about software licenses, I like https://choosealicense.com, who recommend GPL-3 or MIT if you want an open license. I also quite like this short list of recommendations for FAIR software: https://fair-software.eu/

**Comment by cromanpa94** [comment]
Thanks for pointing this out @japhir! We are now providing a license for the `dev` version of `BayClump` and will release the one for the `main` branch by the end of the day!
