### ISSUE TITLE
Sample-level reconstruction datasets

### ISSUE THREAD

**Issue by cromanpa94** [Tripati-Lab/BayClump#18]
The reconstruction tab expected sample-level datasets instead of replicate-level ones. This needs to be clear in the documentation and also in the app.

**Comment by hannahcarroll** [comment]
Related: Guidance needs to be provided in documentation about the use of dummy variables for error where samples have only 1 replicate and error is not reported

**Comment by cromanpa94** [comment]
Added x2 https://github.com/Tripati-Lab/BayClump/commit/80b81d62cff05fbdaa793c0022df795ab755cf24 Feel free to include additional details if necessary!
