### ISSUE TITLE
calculate error for non-bayesian ways in a different way from clumpedr's revcal

### ISSUE THREAD

**Issue by japhir** [Tripati-Lab/BayClump#7]
Hi! I've also emailed you about this, but I thought I'd create an issue for easy tracking:
In the function on line 
https://github.com/Tripati-Lab/BayClump/blob/260092b1cc1111acdad108018998a78406b3bb95/Functions/PredictionFunctions.R#L21
you use `clumpedr::revcal` with `ignorecnf = FALSE`. This is a very sloppy way of propagating uncertainties that I wrote a long time ago and demonstrably overestimates the errors, because it generates the worst-possible-scenario with the largest errors. It ignores the covariance between slope and intercept.
If you only do this for the non-bayesian approach, this results in an unfair comparison.
I hope I've submitted this issue in time for the revisions to the paper!

**Comment by hannahcarroll** [comment]
Thanks so much for bringing this to our attention! This function has been replaced and we are testing the updated function. Apologies for not closing this sooner.

**Comment by japhir** [comment]
Great! Sorry for the inconvenience of my poorly documented function! I've [added a warning to those calibration functions](https://github.com/isoverse/clumpedr/commit/31a60b10f3d36b395722a1a4ee11884a34480ae9) so that future users won't encounter the same issue!
